#ifndef MIMS_EVS
#define MIMS_EVS

/* names of environment variables used by the program */
                                                                                                  
#define ENVT_MIMS_PROCESSING "MIMS_PROCESSING" /* was ENVT_JOB_TYPE */
#define ENVT_OUTPUT_GRID_NAME "OUTPUT_GRID_NAME"
#define ENVT_SRG_HEADER "WRITE_HEADER"
#define ENVT_SRG_QASUM "WRITE_QASUM"
#define ENVT_SRG_OUTPUTNUM "WRITE_SRG_NUMERATOR"
#define ENVT_SRG_OUTPUTDEN "WRITE_SRG_DENOMINATOR"
#define ENVT_SURROGATE_FILE "SURROGATE_FILE"
#define ENVT_DATA_FILE_NAME_TYPE "DATA_FILE_NAME_TYPE"
#define ENVT_DATA_FILE_NAME "DATA_FILE_NAME"
#define ENVT_DATA_ID_ATTR "DATA_ID_ATTR"
#define ENVT_WEIGHT_FILE_NAME "WEIGHT_FILE_NAME"
#define ENVT_WEIGHT_FILE_TYPE "WEIGHT_FILE_TYPE"
#define ENVT_WEIGHT_ATTR_LIST "WEIGHT_ATTR_LIST"
#define ENVT_OUTPUT_FILE_NAME "OUTPUT_FILE_NAME"
#define ENVT_OUTPUT_FILE_TYPE "OUTPUT_FILE_TYPE"
#define ENVT_DATA_ELLIPSOID "DATA_FILE_ELLIPSOID"
#define ENVT_WEIGHT_FILE_ELLIPSOID "WEIGHT_FILE_ELLIPSOID"
#define ENVT_OUTPUT_ELLIPSOID "OUTPUT_FILE_ELLIPSOID"
#define ENVT_DATA_MAP_PROJ "DATA_FILE_MAP_PRJN"
#define ENVT_WEIGHT_FILE_MAP_PROJ "WEIGHT_FILE_MAP_PRJN"
#define ENVT_OUTPUT_MAP_PROJ "OUTPUT_FILE_MAP_PRJN"
#define ENVT_USE_DW_FILE "USE_DW_FILE"
#define ENVT_SAVE_DW_FILE "SAVE_DW_FILE"
#define ENVT_SURROGATE_ID "SURROGATE_ID"
#define ENVT_REPORT_NAME "REPORT_NAME"
#define ENVT_CURVED_LINES "USE_CURVED_LINES"
#define ENVT_GRID_DOT_FILE "GRID_DOT_FILE"
#define ENVT_FILTER_FILE "FILTER_FILE"
#define ENVT_FILTERED_WEIGHT_SHAPES "FILTERED_WEIGHT_SHAPES"
#define ENVT_WEIGHT_FUNCTION "WEIGHT_FUNCTION"
#define ENVT_OUTPUT_FORMAT "OUTPUT_FORMAT"
#define ENVT_DENOMINATOR_THRESHOLD "DENOMINATOR_THRESHOLD"


/* OVERLAY envt. variables added 3/30/2005 BDB */
#define ENVT_OVERLAY_GRID "OVERLAY_GRID"
#define ENVT_OVERLAY_SHAPE "OVERLAY_SHAPE"
#define ENVT_OVERLAY_TYPE "OVERLAY_TYPE"
#define ENVT_OVERLAY_OUT_CELLID "OVERLAY_OUT_CELLID"
/*#define ENVT_OVERLAY_IN_REVERSE "OVERLAY_IN_REVERSE"*/
#define ENVT_OVERLAY_ATTRS "OVERLAY_ATTRS"
#define ENVT_INPUT_FILE_NAME "INPUT_FILE_NAME"
#define ENVT_INPUT_FILE_TYPE "INPUT_FILE_TYPE"
#define ENVT_OVERLAY_MAP_PRJN "OVERLAY_MAP_PRJN"
#define ENVT_INPUT_FILE_MAP_PRJN "INPUT_FILE_MAP_PRJN"
#define ENVT_OVERLAY_ELLIPSOID "OVERLAY_ELLIPSOID"
#define ENVT_INPUT_FILE_ELLIPSOID "INPUT_FILE_ELLIPSOID"
#define ENVT_INPUT_FILE_DELIM "INPUT_FILE_DELIM"
#define ENVT_INPUT_FILE_XCOL "INPUT_FILE_XCOL"
#define ENVT_INPUT_FILE_YCOL "INPUT_FILE_YCOL"
#define ENVT_INPUT_GRID_NAME "INPUT_GRID_NAME"
#define ENVT_OVERLAY_OUT_TYPE "OVERLAY_OUT_TYPE"
#define ENVT_OVERLAY_OUT_NAME "OVERLAY_OUT_NAME"
#define ENVT_OVERLAY_OUT_DELIM "OVERLAY_OUT_DELIM"
#define ENVT_OVERLAY_DELIM "OVERLAY_DELIM"
#define ENVT_OVERLAY_OUT_HDR "OVERLAY_OUT_HDR"
#define ENVT_WRITE_HEADER "WRITE_HEADER"
#define ENVT_DEBUG_OUTPUT "DEBUG_OUTPUT"
#define ENVT_MAX_INPUT_FILE_SHAPES "MAX_INPUT_FILE_SHAPES"


#define ENVT_X_GRID_PARTITIONS "X_GRID_PARTITIONS"
#define ENVT_Y_GRID_PARTITIONS "Y_GRID_PARTITIONS"

#define ENVT_ALLOC_MODE_FILE "ALLOC_MODE_FILE"
#define ENVT_OUTPUT_POLY_ELLIPSOID "OUTPUT_POLY_ELLIPSOID"
#define ENVT_OUTPUT_POLY_TYPE "OUTPUT_POLY_TYPE"
#define ENVT_OUTPUT_POLY_MAP_PRJN "OUTPUT_POLY_MAP_PRJN"
#define ENVT_OUTPUT_POLY_FILE "OUTPUT_POLY_FILE"
#define ENVT_OUTPUT_POLY_ID_ATTR "OUTPUT_POLY_ID_ATTR"
#define ENVT_OUTPUT_POLY_ATTRS "OUTPUT_POLY_ATTRS"
#define ENVT_OUTPUT_POLY_ATTR "OUTPUT_POLY_ATTR"
#define ENVT_ALLOCATE_ATTRS "ALLOCATE_ATTRS"
#define ENVT_ALLOC_ATTR_TYPE "ALLOC_ATTR_TYPE"
#define ENVT_MAX_LINE_SEG "MAX_LINE_SEG"





#endif
